### PR TITLE
Adding path prefix support for schema registry API

### PR DESCRIPTION
**Pull request by scathatheworm**
In the current implementation, if the schema registry itself is not provided at the root of a site, the client is unable to prefix the API calls with the URI path and as such fails all requests. This simple fix allows to support that scenario, which is possible when using a custom but compatible api, a reverse proxy modifying the path, and possible others.

### CODE REVIEW

**Comment by scathatheworm** [comment]
@wvanbergen do you mind taking a look? seems like travis ci is unable to spin up zookeper.

**Comment by wvanbergen** [comment]
Sorry, I am not super actively maintaining this gem as I don't really work with Kafka anymore. 
As a result, I am not really in a position to test this. Can you add tests that show this works as expected?

**Comment by scathatheworm** [comment]
@wvanbergen fixed existing tests, added same tests but going through a reverse proxy, and bumped version to 0.1.1

**Review by wvanbergen — APPROVED** [review]

**Comment by wvanbergen** [comment]
Thanks for contributing! I release the new version to Rubygems.

**Pull request merged**
